### ISSUE TITLE
Investigate image conversion error

### ISSUE THREAD

**Issue by wifasoi** [SpinalHDL/SpinalDoc-RTD#12]
A commit introduce a error
``` text
WARNING: convert exited with error:
[stderr]
Unit… specificata non valida. (italian for Specified unit not valid)
```
this is between 2ba70f7 (bad, acutal dev HEAD) and d161f14 (good, master HEAD 1.3.0 tag)
Tote to self: run git bisect and find the commit responsible for this

**Comment by numero-744** [comment]
Any updates about this issue?

If the error still exists, please open an issue in https://github.com/SpinalHDL/SpinalHDL/issues

Else this issue can be closed.

**Comment by Dolu1990** [comment]
> If the error still exists, please open an issue in https://github.com/SpinalHDL/SpinalHDL/issues

But it is a SpinalDoc-RTD issue isn't it ?

**Comment by numero-744** [comment]
Yes sorry, my bad.

I did not understand the error message was from a docs generator and not SpinalHDL or Scala :disappointed:

**Comment by Dolu1990** [comment]
No worries ^^
