### ISSUE TITLE
Document CombInit

### ISSUE THREAD

**Issue by numero-744** [SpinalHDL/SpinalDoc-RTD#144]

**Comment by Readon** [comment]
The main issue would be in which case user should use CombInit, in which it is not necessary.

**Comment by numero-744** [comment]
I think I address it in the branch I'm working on, that I'll publish as a PR in the next weeks (refactor step 2). I'll let you tell me then :wink:

**Comment by Readon** [comment]
> I think I address it in the branch I'm working on, that I'll publish as a PR in the next weeks (refactor step 2). I'll let you tell me then 😉

Good work.

**Comment by Dolu1990** [comment]
@Readon To me there is a few main usages : 
- Creating a combinatorial value copy of a signal, that you can then override without impacting the source value
- Creating a combinatorial value copy of something that you can then name as you whish for (debug purpose / visibility)

**Comment by Readon** [comment]
> @Readon To me there is a few main usages :
> 
> * Creating a combinatorial value copy of a signal, that you can then override without impacting the source value
> * Creating a combinatorial value copy of something that you can then name as you whish for (debug purpose / visibility)

Like to generate a new wire through existing wire/reg in netlist?

**Comment by numero-744** [comment]
> @Readon To me there is a few main usages :
> 
>     * Creating a combinatorial value copy of a signal, that you can then override without impacting the source value
> 
>     * Creating a combinatorial value copy of something that you can then name as you whish for (debug purpose / visibility)

Thanks I'll add that

**Comment by Dolu1990** [comment]
> that you can then override without impacting the source value

I would say  : 
that you can then conditionaly override without impacting the source value

> Like to generate a new wire through existing wire/reg in netlist?

Yes

**Comment by ronan-lashermes** [comment]
I missed this issue, but there is a short documentation of CombInit in #228.

**Comment by andreasWallner** [comment]
Fixed by @ronan-lashermes with #228
