### ISSUE TITLE
Document compile SpinalHDL by mill.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalDoc-RTD#152]
Do not merge until SpinalHDL/SpinalHDL#969 has not been merged.

**Comment by numero-744** [comment]
Isn't it more related to SpinalTemplateSbt than to SpinalHDL? I think it is already supported? https://github.com/SpinalHDL/SpinalTemplateSbt/blob/master/build.sc

**Comment by Readon** [comment]
> Isn't it more related to SpinalTemplateSbt than to SpinalHDL? I think it is already supported? https://github.com/SpinalHDL/SpinalTemplateSbt/blob/master/build.sc

It's about compile SpinalHDL itself by mill, not user's design.

**Comment by numero-744** [comment]
For this section? https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/About%20SpinalHDL/faq.html#how-to-use-an-unreleased-version-of-spinalhdl-but-committed-on-git

**Comment by Readon** [comment]
> For this section? https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/About%20SpinalHDL/faq.html#how-to-use-an-unreleased-version-of-spinalhdl-but-committed-on-git

Yes, almost, it's another way to speed up compiling time of the lib, while developing.
However, the official publishing can be remained.
