### ISSUE TITLE
Faq: publishLocal must match project's scala version

### ISSUE THREAD

**Issue by numero-744** [SpinalHDL/SpinalDoc-RTD#157]
I did `sbt clean publishLocal` so it published for `2.11` but my project is using `2.12` so it didn't work.

**Comment by Readon** [comment]
it depends on what do you want.
if you just want it once, just modify compiler's index in build.sbt.
if you want to deliver an argument to sbt to switch the compiler than more work is necessary.
also, if an auto detection is prefer than things get complicated.



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 24, 2022 21:38 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [SpinalHDL/SpinalDoc-RTD] Faq: publishLocal must match project'sscala version (Issue #157)




 
I did sbt clean publishLocal so it published for 2.11 but my project is using 2.12 so it didn't work.

**Comment by numero-744** [comment]
Hmm I think we should not implement things, just document something like:

> If you are using scala xxxx then in `build.sbt` change xxx to xxx

or provide a command like:

`sbt clean '++ 2.12.13' publishLocal`

What do you think is better?

**Comment by Readon** [comment]
> `sbt clean '++ 2.12.13' publishLocal`
> 
> What do you think is better?

This would be the better solution.
