### ISSUE TITLE
BufferCC can not be used for general multi Bits sync

### ISSUE THREAD

**Issue by jijingg** [SpinalHDL/SpinalDoc-RTD#16]
i found BufferCC is Recommend for cross clock domain, https://spinalhdl.github.io/SpinalDoc-RTD/SpinalHDL/Structuring/clock_domain.html?highlight=buffercc

BufferCC can be used for single bit or Bits with Gray-coded Sync.

**Comment by Dolu1990** [comment]
Right, there is a few other cross clock useable with Flow and Stream.
The doc should be more precise

**Comment by Dolu1990** [comment]
A third use case could be just to avoid propagating metastable states futher

**Comment by wifasoi** [comment]
I'll add it to my backlog (if someone doesn't volunteer).
Should I add just a note block and recommend to use a stream/flow CCbuffer?

**Comment by Dolu1990** [comment]
Sound good for me :)
