### ISSUE TITLE
Add FAQ for vpi errors on get_time_precision.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalDoc-RTD#170]
As SpinalHDL/SpinalHDL#1022 discussed, the VPI code would remain in simulation directory (such as simWorkspace) without updated while version bumped.

It's reasonable to add a guideline on how to dear with it.

However, it is neither "Design Errors" nor "FAQ"(some bigger question is answered there).
Where to put this is a problem, do you have any idea?

**Comment by Dolu1990** [comment]
Hi,

Hmm that's a tricky one. i would say one good thing is to have a clear github issue with the error message and how to resolve it.

So people which hit the bug can easily find it, + its resolution ?

**Comment by Readon** [comment]
I modified the SpinalHDL/SpinalHDL#973
