### ISSUE TITLE
The CI flow get stuck in these days.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalDoc-RTD#173]
It reports that "detected dubious ownership" while "Build multiversioned doc" stage.
I did not know in which stage the docs directory is created, as well as why its ownership changed.
@numero-744 do you have any idea?

**Comment by numero-744** [comment]
WIP

**Comment by Readon** [comment]
Fixed by #174.
Thanks.

**Comment by Dolu1990** [comment]
<3
