### ISSUE TITLE
How did you draw all these schematics? What tools do you use?

### ISSUE THREAD

**Issue by dzx-dzx** [SpinalHDL/SpinalDoc-RTD#199]
They all look very decent. 
I actually believe I have seen the answer before... But my apologies, I really can't remember where.

**Comment by Dolu1990** [comment]
No worries :)

They mostly come from https://github.com/SpinalHDL/SpinalDoc/tree/master/asset  diagramX.odg .

But now i moved to draw.io
Mostly since NaxRiscv : https://github.com/SpinalHDL/NaxRiscv-Rtd/blob/main/source/asset/miaou.drawio

**Comment by dzx-dzx** [comment]
Thanks for your reply!
I'd admit I prefer the old style a bit, but that's just my own thought. Maybe I'm too familiar with drawio.
