### ISSUE TITLE
readResetWire and readSoftResetWire descriptions are inverted.

### ISSUE THREAD

**Issue by marklinmax** [SpinalHDL/SpinalDoc-RTD#211]
Descriptions are inverted as can be seen here:

> https://github.com/SpinalHDL/SpinalDoc-RTD/blob/10051d6e27554a8d83886a60366e88e3cdb4265d/source/SpinalHDL/Structuring/clock_domain.rst?plain=1#L349C4-L353C53

**Comment by andreasWallner** [comment]
Thanks for dropping the note! will be fixed with the PR above^
