### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by wifasoi** [SpinalHDL/SpinalDoc-RTD#3]
Hi, sorry if i mention you in this issue, but we need you to approve the license change to from MIT to CC0 (for this fork).
If you're ok with this please reply, otherwise we can discuss this here.
@lambdaShade 
@pmudry 
@Snoopy87 
@Dolu1990 (pro-forma)

Thank you for your time.
Luca Cristaldi(wifasoi)

**Comment by Dolu1990** [comment]
+1 :)

**Comment by Dolu1990** [comment]
So, the idea about making it CC0 is to make it as easy as possible to reuse and share.

**Comment by numero-744** [comment]
Has the license been changed?

RTD indicates "© Copyright 2022, SpinalHDL" and there is no LICENCE file in the root of the repository

**Comment by Dolu1990** [comment]
i think the license didn't changed, but we can go CC0

**Comment by wifasoi** [comment]
Unfortunally no one responded. I can add the CCO licence now.. and it will be truw for all new contribution

**Comment by Dolu1990** [comment]
>  I can add the CCO licence now.. and it will be true for all new contribution.

Ok to me :)

**Comment by numero-744** [comment]
Can be closed as done in 6e4d40382409764f10966849410fe1b996a5dfbf
