### ISSUE TITLE
possible typo in getting started

### ISSUE THREAD

**Issue by tulth** [SpinalHDL/SpinalDoc-RTD#33]
At this line, should this be a change directory to ```SpinalTemplateSbt``` instead of ```SpinalBaseProject```?
https://github.com/SpinalHDL/SpinalDoc-RTD/blame/master/source/SpinalHDL/Getting%20Started/getting_started.rst#L62

Or perhaps the intent is to rename it?  or perhaps change the clone to:
```
   git clone https://github.com/SpinalHDL/SpinalTemplateSbt.git SpinalBaseProject
```

**Comment by Dolu1990** [comment]
Right ^^
I will fix it
Thanks :)

**Comment by Dolu1990** [comment]
#32
