### ISSUE TITLE
ScalaDoc hosting

### ISSUE THREAD

**Issue by wifasoi** [SpinalHDL/SpinalDoc-RTD#6]
I think having a ScalaDoc page hosted (maibe on SpinalHDL repo) can be handy. Should we add it to the CI/CD flow?

**Comment by Dolu1990** [comment]
So instead of hosting on https://spinalhdl.github.io/SpinalDoc-RTD/, hosting directly on https://spinalhdl.github.io/SpinalHDL/ ?

**Comment by wifasoi** [comment]
I don't mean this documentation. I mean to have something similar to [this](https://www.scala-lang.org/api/current/scala/collection/parallel/immutable/index.html)

and it easier to have only site per repo (I can use [sbt-site](https://www.scala-sbt.org/sbt-site/index.html), to maintain two site in one gh-pages.. but i prefer to keep it simple and have one gh-paage per repo)

So (to be clear), my idea is to:
* Host/generate the scaladoc documentation on https://spinalhdl.github.io/SpinalHDL/ (SpinalHDL repo)
* Keep the high-level documentation here https://spinalhdl.github.io/SpinalDoc-RTD/ (SpinalDoc-RTD repo)

**Comment by Dolu1990** [comment]
Ahhh right. i got it now, Yes i agree, and it was already requested by other peoples :)

**Comment by Dolu1990** [comment]
I will try to do that.

**Comment by wifasoi** [comment]
SpinalHDL scaladoc is hosted here: http://spinalhdl.github.io/SpinalHDL/
so, I'll close this issue.

**Comment by piegamesde** [comment]
Please link it somewhere on <spinalhdl.github.io>. I had to find this issue to get a link to the ScalaDoc, which is not ideal.
